/*
 * Copyright (C) 2016 Next Thing Co.
 * Jose Angel Torres <software@nextthing.co>
 * 
 * SPDX-License-Identifier:	GPL-2.0+
 */

#include "splash.h"
#include "compiler.h"
#include <stdio.h>
#include <sys/types.h>
#include <dirent.h>

void get_bitmap_info(bitmap_t *b, uint16_t *n_colors, uint16_t *data_offset, FILE *fp);

void print_header(void);
void print_footer(void);
void print_bitmap_data(bitmap_t *b, uint16_t n_colors, uint16_t data_offset, FILE *fp);

/*
 * Neutralize little endians.
 */
uint16_t le_short(uint16_t x)
{
    uint16_t val;
    uint8_t *p = (uint8_t *)(&x);

    val =  (*p++ & 0xff) << 0;
    val |= (*p & 0xff) << 8;

    return val;
}

void skip_bytes (FILE *fp, int n)
{
        while (n-- > 0)
                fgetc (fp);
}

int ends_with(const char* name, const char* extension, size_t length)
{
  const char* ldot = strrchr(name, '.');
  if (ldot != NULL)
  {
    if (length == 0)
      length = strlen(extension);
    return strncmp(ldot + 1, extension, length) == 0;
  }
  return 0;
}

int is_bmp(const char *name)
{
        return ends_with(name, "bmp", 3);
}

int main (int argc, char *argv[])
{
	FILE	*fp;
	bitmap_t bmp;
	bitmap_t *b = &bmp;
	uint16_t data_offset, n_colors;
	DIR *dp;
	struct dirent *ep;
	
	dp = opendir (argv[1]);
	if (dp != NULL)
	{
		while ((ep = readdir (dp))) {
			if (is_bmp(ep->d_name))
				fprintf(stderr, "%s,%i\n", ep->d_name, is_bmp(ep->d_name));
		}	
		(void) closedir (dp);
	}
	else 
        {
		 fprintf(stderr, "%s\n", "Couldn't open the directory");
		 exit (EXIT_FAILURE);
	}
	//parse bitmaps in splash directory
	
	fp = fopen("./tools/images/bolt.bmp" , "rb");
	if (!fp) {
		perror("./tools/images/bolt.bmp");
		exit (EXIT_FAILURE);
	}

	get_bitmap_info(b, &n_colors, &data_offset, fp);
	
	//gen_info

	print_header();

	//Generate Bitmap Data

	print_bitmap_data(b, n_colors, data_offset, fp);

	print_footer();	
	
out:
		fclose(fp);
		return 0;
}

void get_bitmap_info(bitmap_t *b, uint16_t *n_colors, uint16_t *data_offset, FILE *fp) {

	//Check if bitmap file
	if (fgetc (fp) != 'B' || fgetc (fp) != 'M') {
                fprintf(stderr, "%s\n", "Input file is not a bitmap");
                exit(EXIT_FAILURE);
        }

        /*
         * read width and height of the image, and the number of colors used;
         * ignore the rest
         */
        skip_bytes (fp, 8);
        if (fread (data_offset, sizeof (uint16_t), 1, fp) != 1)
                fprintf(stderr, "%s\n", "Couldn't read bitmap data offset\n");
        skip_bytes (fp, 6);
        if (fread (&b->width,   sizeof (uint16_t), 1, fp) != 1)
                fprintf(stderr, "%s\n", "Couldn't read bitmap width\n");
        skip_bytes (fp, 2);
        if (fread (&b->height,  sizeof (uint16_t), 1, fp) != 1)
                fprintf(stderr, "%s\n", "Couldn't read bitmap height\n");
        skip_bytes (fp, 22);
        if (fread (n_colors, sizeof (uint16_t), 1, fp) != 1)
                fprintf(stderr, "%s\n", "Couldn't read bitmap colors\n");
        skip_bytes (fp, 6);

        /*
         * Repair endianess.
         */
        *data_offset = le_short(*data_offset);
        b->width = le_short(b->width);
        b->height = le_short(b->height);
        *n_colors = le_short(*n_colors);

        /* assume we are working with an 8-bit file */
        if ((*n_colors == 0) || (*n_colors > 256 - DEFAULT_CMAP_SIZE)) {
                /* reserve DEFAULT_CMAP_SIZE color map entries for default map */
                *n_colors = 256 - DEFAULT_CMAP_SIZE;
        }
}  


void print_header(void) {
	printf("/*\n"
                        " * Automatically generated by \"tools/splash\"\n"
                        " *\n"
                        " * DO NOT EDIT\n"
                        " *\n"
                        " */\n\n\n"
                        "#ifndef __SPLASH_IMAGE_DATA_H__\n"
                        "#define __SPLASH_IMAGE_DATA_H__\n\n");



}

void print_footer(void) {
        printf("#endif /* __SPLASH_IMAGE_DATA_H__ */\n");
}

void print_bitmap_data(bitmap_t *b, uint16_t n_colors, uint16_t data_offset, FILE *fp) {
	int i, x;
     	/* allocate memory */
        if ((b->data = (uint8_t *)malloc(b->width * b->height)) == NULL)
                perror ("Error allocating memory for file");

	//TODO: Get filename and replace below in platette variable

        /* read and print the palette information */
        printf("unsigned short splash_palette[] = {\n");

        for (i=0; i<n_colors; ++i) {
                b->palette[(int)(i*3+2)] = fgetc(fp);
                b->palette[(int)(i*3+1)] = fgetc(fp);
                b->palette[(int)(i*3+0)] = fgetc(fp);
                x=fgetc(fp);

                printf ("%s0x0%X%X%X,%s",
                        ((i%8) == 0) ? "\t" : "  ",
                        (b->palette[(int)(i*3+0)] >> 4) & 0x0F,
                        (b->palette[(int)(i*3+1)] >> 4) & 0x0F,
                        (b->palette[(int)(i*3+2)] >> 4) & 0x0F,
                        ((i%8) == 7) ? "\n" : ""
                );
        }

        /* seek to offset indicated by file header */
        fseek(fp, (long)data_offset, SEEK_SET);

        /* read the bitmap; leave room for default color map */
        printf ("\n");
        printf ("};\n");
        printf ("\n");
	//TODO: Get filename and replace below in bitmap variable
        printf("unsigned char bmp_logo_bitmap[] = {\n");
        for (i=(b->height-1)*b->width; i>=0; i-=b->width) {
                for (x = 0; x < b->width; x++) {
                        b->data[i + x] = (uint8_t) fgetc(fp)
                                                + DEFAULT_CMAP_SIZE;
                }
        }

        for (i=0; i<(b->height*b->width); ++i) {
                if ((i%8) == 0)
                        putchar ('\t');
                printf ("0x%02X,%c",
                        b->data[i],
                        ((i%8) == 7) ? '\n' : ' '
                );
        }

        printf ("\n"
                "};\n\n"
	);

}
